In [1]:
import random
import numpy as np

def generarDatos():
    random.seed(128)

    marcas = ['Kia', 'Chevrolet', 'Mazda', 'VW', 'Chery', 'Hyundai', 'Jeep', 'Toyota', 
              'Honda', 'Ford', 'Audi', 'Mercedez Benz', 'Renault', 'Citroen', 
              'Nissan', 'Great Wall', 'Seat', 'Changan', 'Skoda', 'Fiat']

    costa = ['Esmeraldas', 'Chone', 'Portoviejo', 'Manta', 'Bahia de Caraquez', 'Guayaquil', 'Salinas', 'Quevedo',
    'Babahoyo', 'Ventanas', 'La Libertad', 'Playas', 'Machala', 'Zaruma', 'Santa Rosa']

    sierra = ['Tulcan', 'Ibarra', 'Quito', 'Latacunga', 'Ambato', 'Riobamba', 'Baños', 'Azogues', 'Cuenca', 'Loja']

    oriente = ['Macas', 'Nueva Loja', 'Puyo', 'Tena', 'Zamora']

    ciudades = costa + sierra + oriente

    arr = np.zeros((len(marcas), len(ciudades)), int)

    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            marca = marcas[i]
            if marca in ['Mercedez Benz', 'Audi']:
                arr[i, j] = int(abs(random.gauss(50, 35)))
            elif marca in ['Kia', 'Chevrolet', 'Chery', 'Hyundai', 'Renault', 'Nissan', 'Great Wall', 'Changan']:
                arr[i, j] = int(abs(random.gauss(600, 200)))
            else:
                arr[i, j] = int(abs(random.gauss(200, 100)))

    return marcas, costa, sierra, oriente, arr

In [2]:
marcas, costa, sierra, oriente, arr_ventas = generarDatos()

In [3]:
marcas

['Kia',
 'Chevrolet',
 'Mazda',
 'VW',
 'Chery',
 'Hyundai',
 'Jeep',
 'Toyota',
 'Honda',
 'Ford',
 'Audi',
 'Mercedez Benz',
 'Renault',
 'Citroen',
 'Nissan',
 'Great Wall',
 'Seat',
 'Changan',
 'Skoda',
 'Fiat']

In [4]:
print(arr_ventas[:5,:5]) #20,30
ciudades = costa+sierra+oriente
#filas = marcas de vehiculos
#columnas = provincias de ecuador'''
print('Bienvenido'.center(50,'*'))
print()

[[736 545 492 592 713]
 [531 571 459 528 616]
 [267 363  86 109 227]
 [ 35  81 224 103 226]
 [927 979 412 628 662]]
********************Bienvenido********************



In [5]:
# 1. ¿Cuál es el total de vehículos vendidos?
total = arr_ventas.sum()
print('El total de vehículos vendidos es : {}'.format(total))


El total de vehículos vendidos es : 205891


In [6]:
#Pide una marca al usuario, y muestra el total de vehículos vendidos para esa marca
marca  = input('Ingrese una marca de vehiculo: ').title()
indice = marcas.index(marca)
fila = arr_ventas[indice,:]
total = fila.sum()
print('El total de vehículos es vendidos de {} es {}'.format(marca,total))

Ingrese una marca de vehiculo: kia
El total de vehículos es vendidos de Kia es 17848


In [7]:
#3. Pide una región al usuario, y muestra el total de vehículos vendidos para esa región
region = input('Ingrese una region: ').lower()
regiones  = costa+sierra+oriente
if region == 'costa':
  cost =  arr_ventas[:,:len(costa)]
  suma = cost.sum()
  print('El total de vehículos vendidos para esa región es: ',suma)
elif region == 'sierra':
  sier = arr_ventas[:,len(costa):len(costa)+len(sierra)]
  suma = sier.sum()
  print(print('El total de vehículos vendidos para esa región es: ',suma))
else:
  ori = arr_ventas[:,len(costa)+len(sierra):]
  suma = ori.sum()
  print(print('El total de vehículos vendidos para esa región es: ',suma))


Ingrese una region: costa
El total de vehículos vendidos para esa región es:  102145


In [8]:
#4. Mostrar cuál es la marca más vendida en cada ciudad
def vehiculos(arr_ventas):
  l_mas_vendidas = []
  col = arr_ventas.shape[1]
  for i in range(col):
    columna = arr_ventas[:,i]
    mayor = columna.argmax()
    vehi = marcas[mayor]
    l_mas_vendidas.append(vehi)
  return l_mas_vendidas
l_mas_vendidas =  vehiculos(arr_ventas)

def datos(l_mas_vendidas,ciudades):
  for k in range(len(ciudades)):
    ciu = ciudades[k]
    vehiculos = l_mas_vendidas[k]
    print('Ciudad: ',ciu)
    print('Marca mas vendida: ',vehiculos)
print(datos(l_mas_vendidas,ciudades))

Ciudad:  Esmeraldas
Marca mas vendida:  Chery
Ciudad:  Chone
Marca mas vendida:  Chery
Ciudad:  Portoviejo
Marca mas vendida:  Hyundai
Ciudad:  Manta
Marca mas vendida:  Renault
Ciudad:  Bahia de Caraquez
Marca mas vendida:  Changan
Ciudad:  Guayaquil
Marca mas vendida:  Hyundai
Ciudad:  Salinas
Marca mas vendida:  Nissan
Ciudad:  Quevedo
Marca mas vendida:  Chery
Ciudad:  Babahoyo
Marca mas vendida:  Renault
Ciudad:  Ventanas
Marca mas vendida:  Chevrolet
Ciudad:  La Libertad
Marca mas vendida:  Renault
Ciudad:  Playas
Marca mas vendida:  Nissan
Ciudad:  Machala
Marca mas vendida:  Chevrolet
Ciudad:  Zaruma
Marca mas vendida:  Chery
Ciudad:  Santa Rosa
Marca mas vendida:  Chevrolet
Ciudad:  Tulcan
Marca mas vendida:  Kia
Ciudad:  Ibarra
Marca mas vendida:  Chevrolet
Ciudad:  Quito
Marca mas vendida:  Renault
Ciudad:  Latacunga
Marca mas vendida:  Chevrolet
Ciudad:  Ambato
Marca mas vendida:  Chery
Ciudad:  Riobamba
Marca mas vendida:  Kia
Ciudad:  Baños
Marca mas vendida:  Great Wall


In [9]:
#5. Para cada ciudad, mostrar la cantidad de marcas que han vendido más de 
#100 vehículos

ciu_col = arr_ventas.shape[1]
l_ventas_100 = []
for j in range(ciu_col):
    colu = arr_ventas[:,j]
    cond = colu>=100
    result = colu[cond]
    cant = result.size
    l_ventas_100.append(cant)
print(l_ventas_100)


[14, 16, 15, 15, 16, 18, 17, 19, 17, 15, 16, 15, 19, 17, 17, 15, 15, 18, 15, 16, 17, 18, 17, 15, 18, 16, 18, 15, 15, 17]


In [ ]:
M = np.random.randint(0,10,(3,4))
M

In [ ]:
M>=5

In [ ]:
M[M>=5]

In [ ]:
M[M>=5].size

In [10]:
print('6. Para cada marca, mostrar la ciudad donde han tenido menos ventas\n')
#revisar porque hay ciudades que se repiten
fil_marcas = arr_ventas.shape[0]
menos_ventas = []

for fil in range(fil_marcas):
  files =  arr_ventas[fil,:]
  menor =  files.argmin()
  city =  ciudades[menor]
  menos_ventas.append(city)

l_ciu_marca = []
for m in range(len(marcas)):
  marca =  marcas[m]
  ciuds =  menos_ventas[m]
  l_ciu_marca.append((marca,ciuds))

for tupla in l_ciu_marca:
  print(tupla)

6. Para cada marca, mostrar la ciudad donde han tenido menos ventas

('Kia', 'Santa Rosa')
('Chevrolet', 'Macas')
('Mazda', 'Azogues')
('VW', 'Zaruma')
('Chery', 'Ventanas')
('Hyundai', 'Puyo')
('Jeep', 'Macas')
('Toyota', 'La Libertad')
('Honda', 'Salinas')
('Ford', 'Ibarra')
('Audi', 'Riobamba')
('Mercedez Benz', 'La Libertad')
('Renault', 'Azogues')
('Citroen', 'Cuenca')
('Nissan', 'Zaruma')
('Great Wall', 'La Libertad')
('Seat', 'Chone')
('Changan', 'Playas')
('Skoda', 'Manta')
('Fiat', 'Manta')


In [15]:
#7. Mostrar las ciudades en donde las ventas promedio han sido
# menores al promedio de ventas general, por marca
prom_general = arr_ventas.mean()
filas_marcas = arr_ventas.shape[0]
v_ciudades = np.array(ciudades)
dicc = {}
for i in range(filas_marcas):
    vector = arr_ventas[i,:]
    condi = vector<prom_general #t, f, t ,t
    resul = v_ciudades[condi]
    dicc[marcas[i]] = resul.tolist()
print(dicc)

    

{'Kia': ['Ventanas', 'Santa Rosa'], 'Chevrolet': ['Quevedo', 'Quito', 'Macas'], 'Mazda': ['Esmeraldas', 'Portoviejo', 'Manta', 'Bahia de Caraquez', 'Guayaquil', 'Salinas', 'Quevedo', 'Babahoyo', 'Ventanas', 'La Libertad', 'Playas', 'Machala', 'Zaruma', 'Santa Rosa', 'Tulcan', 'Ibarra', 'Quito', 'Latacunga', 'Ambato', 'Riobamba', 'Baños', 'Azogues', 'Cuenca', 'Loja', 'Macas', 'Puyo', 'Tena', 'Zamora'], 'VW': ['Esmeraldas', 'Chone', 'Portoviejo', 'Manta', 'Bahia de Caraquez', 'Guayaquil', 'Salinas', 'Quevedo', 'Babahoyo', 'Ventanas', 'La Libertad', 'Playas', 'Machala', 'Zaruma', 'Santa Rosa', 'Tulcan', 'Ibarra', 'Quito', 'Latacunga', 'Ambato', 'Riobamba', 'Baños', 'Azogues', 'Cuenca', 'Loja', 'Macas', 'Nueva Loja', 'Puyo', 'Tena', 'Zamora'], 'Chery': ['Ventanas', 'Macas'], 'Hyundai': ['Machala', 'Quito', 'Puyo'], 'Jeep': ['Esmeraldas', 'Chone', 'Portoviejo', 'Manta', 'Bahia de Caraquez', 'Guayaquil', 'Quevedo', 'Babahoyo', 'Ventanas', 'La Libertad', 'Playas', 'Machala', 'Zaruma', 'Santa 

In [19]:
#8. Pide al usuario un número, y muéstrale la misma cantidad de marcas 
#con más ventas totales. Por ejemplo, si el usuario te da 5, 
#muéstrale las 5 marcas más vendidas.

numero = eval(input('Ingrese un numero: '))
ciudades_mayores = []
marcas_fila = arr_ventas.shape[0]
l_ventas_marca = []
for n in range(marcas_fila):
  num =  arr_ventas[n,:]
  sumas = num.sum()
  l_ventas_marca.append(sumas)
  
v_ventas_marcas = np.array(l_ventas_marca)
ind =  v_ventas_marcas.argsort()
v_marcas = np.array(marcas)
mar = v_marcas[ind][::-1]
topn = mar[:numero]
print(topn)
print()

Ingrese un numero: 5
['Renault' 'Changan' 'Chery' 'Hyundai' 'Kia']



In [20]:
# 9. Del resultado de enunciado 8, saca el total de ventas de esas marcas 
# más vendidas.
v_T_marcas = v_ventas_marcas[ind][::-1]
print(v_T_marcas[:numero])

[18753 18712 18569 18155 17848]


In [21]:
#10. Muestra 3 ciudades con promedio de ventas más bajo de autos. 
# Muestra tanto la ciudad como el promedio de ventas, de menor a mayor')
cols = arr_ventas.shape[1]
l_promedios = []
for j in range(cols):
    colu =  arr_ventas[:,j]
    prom_ven_aut = colu.mean()
    l_promedios.append(prom_ven_aut)
v_promedios = np.array(l_promedios)
v_inds = v_promedios.argsort()
v_ciud =  np.array(ciudades)
print(v_ciud[v_inds][:3])
print(v_promedios[v_inds][:3])

['La Libertad' 'Santa Rosa' 'Playas']
[283.55 293.2  296.55]


In [25]:
'''
Para este enunciado, usado lo explicado arriba, obtén las ciudades y marcas que
hayan vendido más de 100 vehículos (no en total, sino en dicha ciudad). Luego
muéstralos:
Guayaquil – Kia: 150
Esmeraladas – Kia: 220
Tulcan Hyundai: 105'''
idsx= np.where(arr_ventas>100)
inds_filas = idsx[0]
inds_colus = idsx[1]
for i in range(len(inds_filas)):# 0
        ind_fila = inds_filas[i]
        ind_col = inds_colus[i] #1
        valor = arr_ventas[ind_fila,ind_col]
        marca = marcas[ind_fila]
        ciudad = ciudades[ind_col]
        print("{} - {}: {}".format(ciudad,marca,valor))
    


Esmeraldas - Kia: 736
Chone - Kia: 545
Portoviejo - Kia: 492
Manta - Kia: 592
Bahia de Caraquez - Kia: 713
Guayaquil - Kia: 620
Salinas - Kia: 501
Quevedo - Kia: 483
Babahoyo - Kia: 444
Ventanas - Kia: 324
La Libertad - Kia: 530
Playas - Kia: 574
Machala - Kia: 726
Zaruma - Kia: 707
Santa Rosa - Kia: 295
Tulcan - Kia: 916
Ibarra - Kia: 555
Quito - Kia: 388
Latacunga - Kia: 702
Ambato - Kia: 774
Riobamba - Kia: 933
Baños - Kia: 411
Azogues - Kia: 520
Cuenca - Kia: 756
Loja - Kia: 425
Macas - Kia: 845
Nueva Loja - Kia: 672
Puyo - Kia: 489
Tena - Kia: 586
Zamora - Kia: 594
Esmeraldas - Chevrolet: 531
Chone - Chevrolet: 571
Portoviejo - Chevrolet: 459
Manta - Chevrolet: 528
Bahia de Caraquez - Chevrolet: 616
Guayaquil - Chevrolet: 405
Salinas - Chevrolet: 578
Quevedo - Chevrolet: 341
Babahoyo - Chevrolet: 405
Ventanas - Chevrolet: 902
La Libertad - Chevrolet: 509
Playas - Chevrolet: 663
Machala - Chevrolet: 817
Zaruma - Chevrolet: 610
Santa Rosa - Chevrolet: 573
Tulcan - Chevrolet: 772
Iba

In [26]:
M = np.array([[1,200],[300,2]])
tupla = np.where(M>=100)
print(tupla)

(array([0, 1], dtype=int64), array([1, 0], dtype=int64))


In [27]:
M[tupla]

array([200, 300])

In [28]:
A = np.random.randint(0,10,(6,7))
A

array([[7, 6, 4, 8, 7, 4, 4],
       [4, 0, 1, 4, 2, 6, 7],
       [4, 6, 9, 5, 4, 8, 8],
       [3, 0, 0, 4, 1, 9, 0],
       [2, 1, 9, 0, 5, 5, 4],
       [9, 0, 2, 3, 0, 6, 4]])

In [29]:
A[[1,2,3],:]

array([[4, 0, 1, 4, 2, 6, 7],
       [4, 6, 9, 5, 4, 8, 8],
       [3, 0, 0, 4, 1, 9, 0]])

In [ ]:
# una funcion recibe la matriz, las  lista marcas  y una tupla con varias marcas
# calcular el total de vantas de las marcas que estan en la tupla
marcas = ['Kia', 'Chevrolet', 'Mazda', 'VW', 'Chery', 'Hyundai', 'Jeep', 'Toyota', 
              'Honda', 'Ford', 'Audi', 'Mercedez Benz', 'Renault', 'Citroen', 
              'Nissan', 'Great Wall', 'Seat', 'Changan', 'Skoda', 'Fiat']
t_marcas = ('Kia','Ford','Renault', 'Changan')
def l_indices(listaGrande,listaPequeña):
    l_inds = []
    for elem in listaPequeña:
        ind = listaGrande.index(elem)
        l_inds.append(ind)
        
def total_marcas(arr_ventas, marcas,t_marcas):
    l_inds=l_indices(marcas,t_marcas)
    M2 = arr_ventas[l_inds,:]
    total_marcas = M2.sum(axis=1)
    return total_marcas
        

   
    
