![](introduccion.PNG)

![](Pregunta1.PNG)

In [43]:
def caculaTotales(categoria): # 'Flores'
    totales = {}
    f = open(categoria+'.txt', 'r')
    f.readline()
    for linea in f:
        comprador,vendedor,producto,Unidadesvendidas,ventas,Fecha = linea.strip().split(',')
        if (comprador,vendedor,producto) not in totales:
            totales[(comprador,vendedor,producto)] = float(ventas)
        else:
            totales[(comprador,vendedor,producto)] += float(ventas)
    return totales


![](Pregunta2.PNG)

In [51]:
def consolidado(nomArchivo, categorias): # 'Datos.csv' ['Maderas','Flores','Frutas']
    dicCategorias = {}
    f = open(nomArchivo,'w')
    for categoria in categorias: # MAderas
        totales = caculaTotales(categoria)
        productos = []
        for (comprador,vendedor,producto),ventas in totales.items():
            if producto not in productos:
                productos.append(producto)
            linea = comprador+','+vendedor+','+categoria+','+producto+','+str(ventas)+'\n'
            f.write(linea)
        dicCategorias[categoria] = productos
    f.close()
    for categoria in dicCategorias: # Flores
        dicCategorias[categoria].sort()
    return dicCategorias

In [61]:
def l_productos(dicCategorias, categorias):
    productos = []
    for categoria in categorias:
        productos_cate = dicCategorias[categoria]
        productos.extend(productos_cate)
    return productos  

In [62]:
def crearDicc(nomArchivo): # 'Datos.csv'
    dicc = {}
    f = open(nomArchivo, 'r')
    for linea in f: # Ecuador,Alemania,Flores,Narcisos,4523.18
        comprador,vendedor,categoria,producto,ventas = linea.strip().split(',')
        if categoria not in dicc:
            dicc[categoria]  = {(comprador, producto) : float(ventas)}
        else:
            if (comprador, producto) not in dicc[categoria]:
                dicc[categoria][(comprador, producto)] = float(ventas)
            else:
                dicc[categoria][(comprador, producto)] += float(ventas)
    f.close()
    return dicc     

In [63]:
def crearMatriz(nomArchivo, dicCategorias, compradores, categorias):
    productos = l_productos(dicCategorias, categorias)
    fils = len(compradores)
    cols = len(productos)
    M = np.zeros((fils,cols))
    dicc = crearDicc(nomArchivo)
    for categoria in categorias:
        for (comprador, producto), ventas in dicc[categoria].items():
            ind_fila = compradores.index(comprador)
            ind_colu = productos.index(producto)
            M[ind_fila, ind_colu] = ventas
    return M, productos

![](ProgramaPrincipal.PNG)

Finalmente, cree un programa principal para responder a las siguientes preguntas:

In [141]:
import numpy as np

In [142]:
def l_compradores(categorias):
    compradores = []
    for categoria in categorias:
        f = open(categoria + '.txt', 'r')
        f.readline()
        for linea in f: # [Ecuador,Alemania,Narcisos,29103,4523.18,10-08-2020]
            datos = linea.strip().split(',') 
            comprador = datos[0]
            if comprador not in compradores:
                compradores.append(comprador)
    return compradores

In [143]:
categorias = ['Maderas', 'Frutas', 'Flores']
nomArchivo = 'Datos.csv'
dicCategorias= consolidado(nomArchivo, categorias)
compradores = l_compradores(categorias)
M, productos = crearMatriz(nomArchivo, dicCategorias, compradores, categorias)

['Rusia',
 'Peru',
 'Colombia',
 'Mexico',
 'Italia',
 'Alemania',
 'Ecuador',
 'Estados Unidos',
 'China',
 'Francia']

In [148]:
M[:5,:5]

array([[ 67819.69, 163367.57,  22549.88,  27318.63,  20220.26],
       [ 22802.49,      0.  ,  99107.22,  75575.91, 132115.17],
       [ 42127.16, 197692.17,      0.  , 303727.48,      0.  ],
       [     0.  ,  68395.  ,  97312.82, 237987.6 , 103849.44],
       [ 53335.9 , 161169.23,  27808.93, 189850.07,  37379.93]])

1. Cuál es el pais con mas ventas en total?

In [149]:
# iterar una matriz por fila
filas = M.shape[0]
for i in range(filas):#0
    fila = M[i,:]

In [155]:
# total por filas
filas = M.shape[0]
v_pais_T = np.zeros(filas) # [0 0 0 0 0 ]
for i in range(filas):#0
    fila = M[i,:]
    suma = fila.sum()
    v_pais_T[i] = suma
# cual es el mayor
ind_max = np.argmax(v_pais_T)
compradores[ind_max]

In [152]:
v_pais_T

array([2969415.37, 3135062.07, 3378674.53, 2665481.13, 3737620.97,
       4024418.21, 2402009.56, 2071550.8 , 3672705.14, 2891092.69])

2. Cual es el producto con menos ventas en total y a que categoria pertence?

In [ ]:
# iterar una matriz por colunma
colus = M.shape[1]
for j in range(colus):#0
    colu = M[:,j]

In [158]:
v_prods_T = M.sum(axis = 0) 

In [159]:
v_prods_T

array([ 303660.56, 1215744.94,  794697.21, 1733278.35,  784084.67,
       1001147.65,  861529.87,  794714.58,  704273.83, 1451324.06,
        913676.43,  830185.88, 1050320.35,  915047.62, 1118244.42,
        650857.37,  961579.62, 1390944.69, 1282728.  , 1496277.33,
        731311.39, 1098933.81, 1736308.03, 1156863.54,  511006.91,
       1680456.36, 1119902.63,  891065.75, 1045616.75,  722247.87])

In [162]:
ind_min_prod = np.argmin(v_prods_T)
min_prod = productos[ind_min_prod]

In [163]:
# a que categoria pertenece
def categoria_prod(dicCategorias,producto):
    for categoria, l_productos in dicCategorias.items():
        if producto in l_productos:
            return categoria

In [165]:
cate_prod = categoria_prod(dicCategorias,min_prod)

'Maderas'

In [166]:
print('El producto con menos ventas en total es {} y a que categoria pertence es {}'.format(min_prod,cate_prod))

El producto con menos ventas en total es Abeto y a que categoria pertence es Maderas


3. Top 5 de los países con más ventas considerando todos los productos.

In [167]:
v_pais_T

array([2969415.37, 3135062.07, 3378674.53, 2665481.13, 3737620.97,
       4024418.21, 2402009.56, 2071550.8 , 3672705.14, 2891092.69])

In [168]:
compradores

['Rusia',
 'Peru',
 'Colombia',
 'Mexico',
 'Italia',
 'Alemania',
 'Ecuador',
 'Estados Unidos',
 'China',
 'Francia']

In [173]:
# sacar top por listas
l_tuplas = []
for i in range(len(compradores)): # 0
    pais = compradores[i] # Rusia
    ventas_pais = v_pais_T[i] # 2969415.37
    tupla = (ventas_pais, pais)
    l_tuplas.append(tupla)
l_tuplas.sort()
orden = l_tuplas[::-1]
top5 = orden[:5]
top5

[(4024418.2100000004, 'Alemania'),
 (3737620.9699999997, 'Italia'),
 (3672705.1400000006, 'China'),
 (3378674.53, 'Colombia'),
 (3135062.0700000003, 'Peru')]

In [179]:
v_paises = np.array(compradores)
v_paises

array(['Rusia', 'Peru', 'Colombia', 'Mexico', 'Italia', 'Alemania',
       'Ecuador', 'Estados Unidos', 'China', 'Francia'], dtype='<U14')

In [181]:
# sacar por numpy
ind_top5 = v_pais_T.argsort()[::-1][:5]

In [182]:
v_paises[ind_top5]

array(['Alemania', 'Italia', 'China', 'Colombia', 'Peru'], dtype='<U14')

4. Solicite al usuario el nombre de un producto y muestre por pantalla los países ordenados acuerdo a las ventas para ese producto.

In [183]:
nom_producto = input('Ingrese un producto: ')

Ingrese un producto: Abeto


In [193]:
ind_prod = productos.index(nom_producto) #0
m_prod = M[:,ind_prod]
m_prod
ind_ord_prod = m_prod.argsort()[::-1]
ord_pais_prod = v_paises[ind_ord_prod]
ord_pais_prod

array(['Rusia', 'Italia', 'China', 'Colombia', 'Alemania',
       'Estados Unidos', 'Peru', 'Ecuador', 'Francia', 'Mexico'],
      dtype='<U14')

In [188]:
m_prod.argsort()[::-1]

array([0, 4, 8, 2, 5, 7, 1, 6, 9, 3], dtype=int64)

In [192]:
v_paises[m_prod.argsort()[::-1]]

array(['Rusia', 'Italia', 'China', 'Colombia', 'Alemania',
       'Estados Unidos', 'Peru', 'Ecuador', 'Francia', 'Mexico'],
      dtype='<U14')

5. Solicite al usuario un pais y muestre por pantalla que productos *no a comprado* en cada categoria-

In [194]:
pais = input('Ingrese un pais: ')

Ingrese un pais: Colombia


In [197]:
# Iterar una matriz por bloque 
ini_col = 0
for categoria in categorias: # maderas
    l_prods_cate = dicCategorias[categoria] #
    fin_col = ini_col + len(l_prods_cate) # 4
    m_categoria = M[:,ini_col: fin_col]
    ini_col = fin_col  

In [199]:
#  muestre por pantalla que productos no a comprado en cada categoria
ind_pais = compradores.index(pais)
ini_col = 0
for categoria in categorias: # maderas
    v_prods_cate = np.array(dicCategorias[categoria]) #
    fin_col = ini_col + len(l_prods_cate) # 4
    m_categoria = M[ind_pais,ini_col: fin_col]
    condicion = m_categoria == 0
    prod_no_comprados = v_prods_cate[condicion]
    print(categoria)
    print(prod_no_comprados)
    ini_col = fin_col  

Maderas
['Caoba' 'Cerezo' 'Nogal' 'Pino']
Frutas
['Grosella' 'Limon']
Flores
[]


6. Cuál es la categoria con más ventas.

In [200]:
# Iterar una matriz por bloque 
ini_col = 0
v_cate_T = np.zeros(len(categorias)) 
for categoria in categorias: # maderas
    l_prods_cate = dicCategorias[categoria] #
    fin_col = ini_col + len(l_prods_cate) # 4
    m_categoria = M[:,ini_col: fin_col]
    suma = m_categoria.sum()
    i = categorias.index(categoria)
    v_cate_T[i] = suma
    ini_col = fin_col  

In [201]:
v_cate_T

array([ 9644455.72, 10609861.71, 10693713.04])

In [204]:
ind_max_cate = v_cate_T.argmax()
cate_Mayor = categorias[ind_max_cate]
cate_Mayor

'Flores'


7. Para cada pais muestre por pantalla con que productos de categoria Frutas superan a su producto más vendido en la categoria Flores. Si un pais no tiene ningun producto de Frutas que cumpla la condicion debe mostrar por pantalla un mensaje adecuado.


![](Pregunta3.PNG)

In [205]:
def matrizCategoria(M,dicCategorias,categorias, nomCategoria): # Flores
    # Iterar una matriz por bloque 
    ini_col = 0
    for categoria in categorias: # maderas
        l_prods_cate = dicCategorias[categoria] #
        fin_col = ini_col + len(l_prods_cate) # 4
        m_categoria = M[:,ini_col: fin_col]
        if nomCategoria == categoria:
            return m_categoria
        ini_col = fin_col  

In [214]:
# producto más vendidos en la categoria Flores
mFlores = matrizCategoria(M,dicCategorias,categorias, 'Flores')
max_Flores = mFlores.max(axis = 1)

In [215]:
mFrutas = matrizCategoria(M,dicCategorias,categorias, 'Frutas')

In [224]:
v_prods_frutas = np.array(dicCategorias['Frutas'])
v_prods_frutas

array(['Cacao', 'Cereza', 'Frambuesa', 'Grosella', 'Kaki', 'Limon',
       'Mandarina', 'Manzana', 'Naranja', 'Papaya'], dtype='<U9')

In [225]:
m_condicion = mFrutas > max_Flores

In [228]:
for i in range(m_condicion.shape[0]):
    fila = m_condicion[i,:]
    prods_frutas_cond = v_prods_frutas[fila] # []
    pais = compradores[i]
    print(pais)
    if len(prods_frutas_cond)== 0:
        print('no hay')
    else:
        print(prods_frutas_cond)

Rusia
no hay
Peru
['Grosella' 'Manzana']
Colombia
no hay
Mexico
no hay
Italia
no hay
Alemania
no hay
Ecuador
['Manzana']
Estados Unidos
['Manzana']
China
['Cereza' 'Papaya']
Francia
no hay
