![](introduccion.PNG)

![](Pregunta1.PNG)

![](Pregunta2.PNG)

![](ProgramaPrincipal.PNG)

Finalmente, cree un programa principal para responder a las siguientes preguntas:

['Rusia',
 'Peru',
 'Colombia',
 'Mexico',
 'Italia',
 'Alemania',
 'Ecuador',
 'Estados Unidos',
 'China',
 'Francia']

array([[ 67819.69, 163367.57,  22549.88,  27318.63,  20220.26],
       [ 22802.49,      0.  ,  99107.22,  75575.91, 132115.17],
       [ 42127.16, 197692.17,      0.  , 303727.48,      0.  ],
       [     0.  ,  68395.  ,  97312.82, 237987.6 , 103849.44],
       [ 53335.9 , 161169.23,  27808.93, 189850.07,  37379.93]])

1. Cuál es el pais con mas ventas en total?

array([2969415.37, 3135062.07, 3378674.53, 2665481.13, 3737620.97,
       4024418.21, 2402009.56, 2071550.8 , 3672705.14, 2891092.69])

2. Cual es el producto con menos ventas en total y a que categoria pertence?

array([ 303660.56, 1215744.94,  794697.21, 1733278.35,  784084.67,
       1001147.65,  861529.87,  794714.58,  704273.83, 1451324.06,
        913676.43,  830185.88, 1050320.35,  915047.62, 1118244.42,
        650857.37,  961579.62, 1390944.69, 1282728.  , 1496277.33,
        731311.39, 1098933.81, 1736308.03, 1156863.54,  511006.91,
       1680456.36, 1119902.63,  891065.75, 1045616.75,  722247.87])

'Maderas'

El producto con menos ventas en total es Abeto y a que categoria pertence es Maderas


3. Top 5 de los países con más ventas considerando todos los productos.

array([2969415.37, 3135062.07, 3378674.53, 2665481.13, 3737620.97,
       4024418.21, 2402009.56, 2071550.8 , 3672705.14, 2891092.69])

['Rusia',
 'Peru',
 'Colombia',
 'Mexico',
 'Italia',
 'Alemania',
 'Ecuador',
 'Estados Unidos',
 'China',
 'Francia']

[(4024418.2100000004, 'Alemania'),
 (3737620.9699999997, 'Italia'),
 (3672705.1400000006, 'China'),
 (3378674.53, 'Colombia'),
 (3135062.0700000003, 'Peru')]

array(['Rusia', 'Peru', 'Colombia', 'Mexico', 'Italia', 'Alemania',
       'Ecuador', 'Estados Unidos', 'China', 'Francia'], dtype='<U14')

array(['Alemania', 'Italia', 'China', 'Colombia', 'Peru'], dtype='<U14')

4. Solicite al usuario el nombre de un producto y muestre por pantalla los países ordenados acuerdo a las ventas para ese producto.

Ingrese un producto: Abeto


array(['Rusia', 'Italia', 'China', 'Colombia', 'Alemania',
       'Estados Unidos', 'Peru', 'Ecuador', 'Francia', 'Mexico'],
      dtype='<U14')

array([0, 4, 8, 2, 5, 7, 1, 6, 9, 3], dtype=int64)

array(['Rusia', 'Italia', 'China', 'Colombia', 'Alemania',
       'Estados Unidos', 'Peru', 'Ecuador', 'Francia', 'Mexico'],
      dtype='<U14')

5. Solicite al usuario un pais y muestre por pantalla que productos *no a comprado* en cada categoria-

Ingrese un pais: Colombia


Maderas
['Caoba' 'Cerezo' 'Nogal' 'Pino']
Frutas
['Grosella' 'Limon']
Flores
[]


6. Cuál es la categoria con más ventas.

array([ 9644455.72, 10609861.71, 10693713.04])

'Flores'


7. Para cada pais muestre por pantalla con que productos de categoria Frutas superan a su producto más vendido en la categoria Flores. Si un pais no tiene ningun producto de Frutas que cumpla la condicion debe mostrar por pantalla un mensaje adecuado.


![](Pregunta3.PNG)

In [205]:
def matrizCategoria(M,dicCategorias,categorias, nomCategoria): # Flores
    # Iterar una matriz por bloque 
    ini_col = 0
    for categoria in categorias: # maderas
        l_prods_cate = dicCategorias[categoria] #
        fin_col = ini_col + len(l_prods_cate) # 4
        m_categoria = M[:,ini_col: fin_col]
        if nomCategoria == categoria:
            return m_categoria
        ini_col = fin_col  

In [214]:
# producto más vendidos en la categoria Flores
mFlores = matrizCategoria(M,dicCategorias,categorias, 'Flores')
max_Flores = mFlores.max(axis = 1)

In [215]:
mFrutas = matrizCategoria(M,dicCategorias,categorias, 'Frutas')

In [224]:
v_prods_frutas = np.array(dicCategorias['Frutas'])
v_prods_frutas

array(['Cacao', 'Cereza', 'Frambuesa', 'Grosella', 'Kaki', 'Limon',
       'Mandarina', 'Manzana', 'Naranja', 'Papaya'], dtype='<U9')

In [225]:
m_condicion = mFrutas > max_Flores

In [228]:
for i in range(m_condicion.shape[0]):
    fila = m_condicion[i,:]
    prods_frutas_cond = v_prods_frutas[fila] # []
    pais = compradores[i]
    print(pais)
    if len(prods_frutas_cond)== 0:
        print('no hay')
    else:
        print(prods_frutas_cond)

Rusia
no hay
Peru
['Grosella' 'Manzana']
Colombia
no hay
Mexico
no hay
Italia
no hay
Alemania
no hay
Ecuador
['Manzana']
Estados Unidos
['Manzana']
China
['Cereza' 'Papaya']
Francia
no hay
