In [2]:
import numpy as np


In [3]:
A = np.random.randint(0,10,(2,3))
A

array([[2, 3, 0],
       [5, 1, 8]])

In [4]:
B = np.random.randint(0,10,(2,3))
B

array([[3, 7, 4],
       [9, 3, 9]])

In [5]:
np.concatenate((A,B),1)

array([[2, 3, 0, 3, 7, 4],
       [5, 1, 8, 9, 3, 9]])

In [6]:
np.concatenate((A,B),0)

array([[2, 3, 0],
       [5, 1, 8],
       [3, 7, 4],
       [9, 3, 9]])

In [7]:
l = np.array([])
a= np.array([5,5,4,2])
l=np.concatenate((l,a))


In [8]:
b =a[a!=5]
np.concatenate((l,b))

array([5., 5., 4., 2., 4., 2.])