In [2]:
import numpy as np

In [ ]:
A = np.random.randint(1,10,(5,3))
A

In [ ]:
# axis = 0 para las columnas
A.sum(axis = 0)

In [ ]:
# axis = 1 para las filas
A.sum(axis = 1)

In [7]:
a = np.array([5,1,6])
b = np.array([3,2,7])
print(a<b)


[False  True  True]


In [4]:
print(a[a<b])

[1 6]


In [6]:
nombres = ["Jose","Pepe","Maria","Marco","Juan","Jhon","Nathaly"]
edades = np.array([15,14,19,18,17,20,22])
condicion = edades>=18


In [12]:
# mostrar quienes son mayores de 18
v_nombres = np.array(nombres)
print(v_nombres)
print(v_nombres[condicion])
print(edades[condicion])

['Jose' 'Pepe' 'Maria' 'Marco' 'Juan' 'Jhon' 'Nathaly']
['Maria' 'Marco' 'Jhon' 'Nathaly']
[19 18 20 22]


In [11]:
#np.where
v_inds= np.where(edades<=18)
print(v_inds)

(array([0, 1, 3, 4], dtype=int64),)


In [13]:
v_nombres[v_inds]

array(['Jose', 'Pepe', 'Marco', 'Juan'], dtype='<U7')

In [19]:
#np.where(condicion, cambia los valores si se cumple,)
np.where(edades>=18,edades,-1)

array([-1, -1, 19, 18, -1, 20, 22])

In [ ]:
# cuantos son mayores de edad
cant = len(v_nombres[condicion])
cant

In [ ]:
A = np.random.randint(1,10,(3,3))
B = np.random.randint(1,10,(3,3))
print(A)
print()
print(B)
C = np.array([["A","B","c"],["D","E","F"],["G","H","I"]])
print()
print(C)

In [ ]:
np.any(A ==0)

In [ ]:
A==B # se comparan los elementos que estan en la misma posicion

In [ ]:
C[A==B] # Devuelve el vector con los elementos que estan en la posicion donde se cumple la condicion

In [ ]:
A[B==A] 


In [ ]:
c = np.ones((3,3))
c

In [ ]:
c==1

In [ ]:
np.all(c==1)

In [ ]:
#np.where()
A = np.random.randint(1,10,10)
print(A)
print(np.where(A>5))
print(np.where(A>5)[0])
print(len(np.where(A>5)[0]))


In [ ]:
#np.where(condicion)
#np.where(condicion,)
B= np.array([[4,5],[5,2]])
print(B)
np.where(B==5)


In [ ]:
M = np.random.randint(0,101,(5,5))
M

In [ ]:
M_nueva = np.where(M>50,0,1) # matriz donde el valor de celda es uno si paso la materia, 0 caso contrario
print(M_nueva)
materias = ["Matematica","Fisica","Quimica","Biologia","comunicacion"] # representan las filas 
estudiantes = ["Pepe","jose","Mario","Lucas","Maria"] # representan las columnas

In [ ]:
# Mostrar las materias que paso cada estudiante
# D = { estudiante1 :  [materia1, materia3]}
# iterar por estudiante columna
d = dict()
v_materias = np.array(materias)
for j in range(len(estudiantes)):
    columna = M_nueva[:,j]
    condicion = columna!=0
    materias_AP = v_materias[condicion]
    estudiante = estudiantes[j]
    d[estudiante] = materias_AP.tolist()
print(d)