In [2]:
import numpy as np
# hacer un funcion promedioProductos(cod, codigos) que recibe un vector de codigos y una lista de codigos, mostrar el promedio de
# todo el año de ESOS codigos
def promedioProductos(cod, codigos, M):# [100034, 100312, 100021]
    v_codigos = np.array(codigos) # [100034 100312 100021]
    v_bools = np.isin(cod,v_codigos)
    print(v_bools)
    indices = np.where(v_bools)
    print(indices[0])
    for i in indices:
        M[i,:]
cod = np.array([100034,100312,100021,201245,432198])
codigos = [100034, 100021, 432198]
promedioProductos(cod, codigos)

[ True False  True False  True]
[0 2 4]


In [ ]:
L_cod= cod.tolist()
for codigo in codigos:
    ind = L_cod.index(codigo) 

In [4]:
M = np.random.randint(1,5,(7,5))
print(M)
print(M.sum(axis = 0)) # columnas

[[3 2 4 4 2]
 [2 1 4 3 1]
 [4 3 1 2 3]
 [3 3 2 1 1]
 [3 3 3 1 2]
 [3 1 3 2 3]
 [2 3 3 1 4]]
[20 16 20 14 16]


In [5]:
print(M.sum(axis = 1))

[15 11 13 10 12 12 13]
