# Numpy

Los arreglos pueden realizar operaciones con datos numéricos mucho más rápido, y en general son más eficientes que las listas.
* Una colección de elementos que son todos del mismo tipo (float o int)
* Una o más dimensiones (2)
* Que son indexados por una tupla de enteros no negativos.

In [2]:
# importar Modulo
import numpy as np

In [2]:
vector1 = np.array([1,5,7,9.5])
vector1

array([1. , 5. , 7. , 9.5])

In [3]:
v = np.array(["a","b","c"])
v

array(['a', 'b', 'c'], dtype='<U1')

In [10]:
# crear un vector
# np.array(Lista, tipo)
vector1 = np.array([1,5,7,9.5],int)
vector2 = vector1.copy()
vector2+=1
print(vector1)
print(vector2)

[ 2  6  8 10]
[ 2  6  8 10]


In [ ]:
# A.tolist()
lista = vector1.tolist()
lista

In [ ]:
notas= np.array([ 4.13 , 3.76, 3.68, 1.62 , 8.77, 8.70, 8.89, 6.75])
notas[-1]

In [11]:
print(vector1.size)

4


In [12]:
print(vector1.shape)

(4,)


In [13]:
M = np.array([[0,1,2,3],[1,1,1,1],[2,2,2,2]],float)
lista = M.tolist()
lista

[[0.0, 1.0, 2.0, 3.0], [1.0, 1.0, 1.0, 1.0], [2.0, 2.0, 2.0, 2.0]]

In [14]:
M.shape

(3, 4)

In [15]:
#Matriz
M = np.array([[2,4,6,8],[8,10,12,14]])
M

array([[ 2,  4,  6,  8],
       [ 8, 10, 12, 14]])

In [ ]:
M.size

In [ ]:
M.shape

In [16]:
C= np.zeros(M.shape)
C

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
C.size

8

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.full(M.shape,10.)

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [25]:
# retorna una matriz 
# np.random.randint(desde, hasta_sinIncluir, size = (fil,cols))
A=np.random.randint(100,1000,(2,3))
A

array([[868, 597, 992],
       [374, 994, 997]])

In [26]:
vector = np.random.randint(3,size=15)
vector

array([0, 2, 1, 2, 0, 1, 0, 1, 1, 1, 2, 0, 1, 0, 1])

In [27]:
# reordena una matriz
B=A.reshape((3,2))
B

array([[868, 597],
       [992, 374],
       [994, 997]])

In [28]:
B.reshape((6,))

array([868, 597, 992, 374, 994, 997])

In [ ]:
C = np.arange(9,0,-1)
C

                 Jose             Juan
             1P    |  2P   | 1P    |  2P
Matematicas: 71.73 | 91.68 | 81.71 | 61.89
    Fisica :

In [30]:
B.dtype

dtype('int32')

In [5]:
A = np.array([1,1,1,1,5,5,5,2,1,5,4,4])
B = np.unique(A)
B

array([1, 2, 4, 5])

In [ ]:
M = np.array([[ 71.73, 91.68, 81.71, 61.89, 21.79, 45.56],
              [ 65.4 , 59.2 , 63.6 , 88.4 , 68.7, 56.78 ],
              [ 68.4 , 79.2 , 53.6 , 48.4 , 98.7, 56.78 ]])
M

nom_Matriz[ini_Fila:Fin_Fila, Ini_Col:Fin_Col]
nom_Matriz[:,:]
nom_Matriz[fila,columna] # sacar un elemento de mi matriz


In [ ]:
# Sacar la segunda fila
# Sacar toda una fila
# M[fila,:]
M[1,:]

In [ ]:
# Sacar toda una columna
# M[:,columna]
# Sacar la tercera columna
M[:,2]

In [ ]:
# Sacar un elemento de la Matriz
# M[fila, columna]
M[1,1]

In [ ]:
# Sacar una parte de la matriz
# Sacar notas de jose
M [:,0:2]

In [ ]:
# Slicing a una Matriz
# M[iniFila: finFila, iniCol: finCol]

In [ ]:
Matriz = np.random.randint(1,10, size = (5,10))
Matriz

In [ ]:
Matriz[1:3,:]

In [ ]:
Matriz[3,:]

In [ ]:
Matriz2 = np.array([[ 1.73, 1.68, 1.71, 1.89, 1.79],
                    [ 65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])
Matriz2[:,1:3] -= 10

print("2....")
print(Matriz2)