In [1]:
import numpy as np

            
    G    [10, 5, 100, 20, 22, 78, 99, 122],
    M    [8, 8, 11, 200, 6, 78, 92, 192],
    Q    [18, 8, 11, 3, 6, 78, 92, 192],
    C    [8, 8, 11, 6, 6, 100, 92, 34],
    T    [8, 65, 11, 200, 6, 7, 92, 69],
    P    [8, 43, 11, 500, 6, 25, 92, 12]

In [9]:

costa = ['Guayaquil', 'Machala']
sierra = ['Quito', 'Cuenca']
oriente = ['Tena', 'Puyo']

ciudades = costa + sierra + oriente

marcas = ['Kia', 'Hyundai', 'Honda', 'Mazda', 'Toyota', 'Audi', 'VW', 'Chevrolet']

ventas_autos = np.array([
    [10, 5, 100, 20, 22, 78, 99, 122],
    [8, 8, 11, 200, 6, 78, 92, 192],
    [18, 8, 11, 3, 6, 78, 92, 192],
    [8, 8, 11, 6, 6, 100, 92, 34],
    [8, 65, 11, 200, 6, 7, 92, 69],
    [8, 43, 11, 500, 6, 25, 92, 12]
])


In [ ]:

# for fila in ventas_autos:
#     for elem in fila:
#         print(elem)

np.random.seed(5)
unidades_defectuosas = np.random.randint(0, 3, ventas_autos.shape)

#¿Cual es total de autos vendidos?
total = ventas_autos.sum()
print('Total autos de autos vendidos %d' %  total)

#¿Cual es porcentaje de autos defectusos para cada ciudada/marca? defec / cantidad * 100
porc_defectuosos = unidades_defectuosas / ventas_autos * 100
#print(porc_defectuosos)

#total autos vendidos en region costa
total = ventas_autos[:len(costa), : ].sum()
print('total ventas costa %d' % total)

#total de lventas de carros para cada ciudade
ventas_ciudad = ventas_autos.sum(axis=1)
print(ventas_ciudad)
for i in range(ventas_ciudad.size):
    print('Ventas totales en %s: %d' % (ciudades[i], ventas_ciudad[i]))

prom_ventas_ciudad = ventas_ciudad.mean()
print('Promedio de ventas por ciudad %d' % prom_ventas_ciudad)

#ciudad y marca con mas ventas
coord = np.unravel_index(ventas_autos.argmax(), ventas_autos.shape)
print(coord)
print('La ciudad que mas vendio es %s y la marca %s' % (ciudades[coord[0]], marcas[coord[1]]))

#las 4 marcas vendidas por ciudad
idx_ordenados = ventas_autos.argsort(axis=1)
print(ventas_autos)
print(idx_ordenados)

top_4_idx = idx_ordenados[:, -4:]       #o si top mas pequenos, [:, 0:4]
print(top_4_idx)

for idx_ciudad in range(top_4_idx.shape[0]):
    ciudad = ciudades[idx_ciudad]
    print('Marca mas vendida para %s: ' % ciudad)
    for j in range(top_4_idx.shape[1]):
        idx_col = top_4_idx[idx_ciudad, j]
        marca = marcas[ idx_col ]
        cantidad = ventas_autos[idx_ciudad, idx_col]
        print('- %s: %d' % (marca, cantidad))


In [7]:
ventas_autos = np.array([
    [10, 5, 100, 20, 22, 78, 99, 122],
    [8, 8, 11, 200, 6, 78, 92, 192],
    [18, 8, 11, 3, 6, 78, 92, 192],
    [8, 8, 11, 6, 6, 100, 92, 34],
    [8, 65, 11, 200, 6, 7, 92, 69],
    [8, 43, 11, 500, 6, 25, 92, 12]
])



In [12]:
ventas_autos.size

48

In [3]:
np.random.seed(5)

None


In [5]:
np.random.seed(5)
unidades_defectuosas = np.random.randint(0, 3, ventas_autos.shape)

In [6]:
unidades_defectuosas

array([[2, 1, 2, 2, 0, 1, 0, 0],
       [2, 0, 2, 0, 0, 1, 1, 0],
       [0, 1, 1, 2, 0, 2, 1, 2],
       [2, 1, 1, 2, 1, 1, 2, 1],
       [2, 0, 2, 1, 2, 0, 0, 0],
       [2, 0, 1, 2, 0, 2, 1, 2]])

In [10]:

#ciudad y marca con mas ventas
coord = np.unravel_index(ventas_autos.argmax(), ventas_autos.shape)
print(coord)
print('La ciudad que mas vendio es %s y la marca %s' % (ciudades[coord[0]], marcas[coord[1]]))

(5, 3)
La ciudad que mas vendio es Puyo y la marca Mazda


In [11]:
ventas_autos.argmax()

43

In [26]:

M = np.array([
    [10, 5, 100, 20, 22, 78, 99, 122],
    [8, 8, 11, 500, 6, 78, 92, 192],
    [18, 8, 11, 3, 6, 78, 92, 192],
    [8, 8, 11, 6, 6, 100, 92, 34],
    [8, 65, 11, 200, 6, 7, 92, 69],
    [8, 43, 11, 500, 6, 25, 92, 12]
])

M.argmax(axis = 0)


array([2, 4, 0, 1, 0, 3, 0, 1], dtype=int64)

In [30]:
# columna
def inds_max(M):
    inds = []
    cols = M.shape[1]
    for j in range(cols): # 0
        col = M[:,j] # [10 8 18 8 8 8]
        ind_max = col.argmax() # 2
        inds.append(ind_max)
    v_inds = np.array(inds)
    return v_inds
        
inds_max(M)       

    

array([2, 4, 0, 1, 0, 3, 0, 1], dtype=int64)

In [ ]:
def ind_mayor_Matrix(M)
    filas = M.shape()[0]
    cols = M.shape()[1]
    maxi = M.max()
    for i in range(filas):
        for j in range(cols):
            if M[i,j] == maxi:
                return (i,j)
            