In [2]:
import numpy as np
nomArchivo = "juanmarcet.csv"
f = open(nomArchivo)
columnas = f.readline().strip().split(',')  # lapiz,pluma,borrador,regla,cartulina,goma,sacapuntas,escuadra
vector_columna = np.array(columnas)
f.readline()
f.readline()
M = np.zeros((1,vector_columna.size))
fila = 0
listVendedores = []
for linea in f: # 20200705,borrador|14;regla|13;cartulina|4;escuadra|4;goma|21
    datos = linea.strip().split(",")
    cod_Vendedor = datos[0]
    articulos = datos[1].split(";")
    listVendedores.append(cod_Vendedor)
    for elemento in articulos:
        art, cant = elemento.split('|')
        cant = int(cant)
        M[fila,vector_columna == art] = cant
    nuevaFila = np.zeros((1,vector_columna.size))
    M = np.concatenate((M, nuevaFila), axis=0)
    fila += 1
f.close()
print(M)
print(np.array(listVendedores))




[[ 0.  0. 14. 13.  4. 21.  0.  4.]
 [12.  6. 17.  9.  0. 15.  6.  3.]
 [ 2. 22. 14. 15.  1.  6.  0.  2.]
 [ 2.  8.  3.  4. 22. 15. 13. 20.]
 [23. 14. 12.  0. 16. 18. 23. 23.]
 [ 0. 12.  0. 16. 19.  1. 12. 19.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
['20200705' '20200519' '20200705' '20200705' '20200519' '20220523']


In [ ]:
def mas_registrado_mes(M, cod_vendedor, v_vendedores, v_articulos):
    areavendedores = M[v_vendedores == cod_vendedor, :]
    areaArticulos = np.where(areavendedores > 0, 1, 0)
    vectortotales = areaArticulos.sum(axis=0)
    indiMaxi = vectortotales.argmax()
    return v_articulos(indiMaxi)