# Taller NumPy 1D

## Ejercicio 1

En este taller usarás lo aprendido en NumPy, para analizar datos. Para esto, se te provee un archivo llamado datos_casas.csv, que contiene las direcciones de casas y los precios. El formato del archivo es:

__direccion,area,cuartos,banos,precio,pais__

Escribiras un programa que, usando NumPy responda las siguientes preguntas. Primero necesitar:

1. ¿Cuál es el precio promedio de todas las casas?

2. ¿Cuál es el área total de las casas con 3 cuartos?

3. ¿Cuántas casas tienen precios mayores a $100000, y 2 cuartos?

4. Muestre las direcciones de las 4 casas más baratas, y sus precios.

5. De Las casas con 3 y 4 cuartos, muestre los países de las 2 casas con mayor precio.

6. DE las casas que tiene un precio menor al promedio de todas las casas, muestre el promedio de precio y de habitaciones.

7.	Debemos calcular el precio final de ventas de las casas. Para esto se necesitamos aplicar los siguientes impuestos:

    * Si la casa cuesta menos de $100 000, solo paga IVA 12%
    * Si cuesta más de $100 000, debe aplicar IVA (12%) y plusvalía (15%).
Genera un nuevo arreglo con los precios de las casas. Muestre cuál es el precio promedio de las casas una vez aplicado los impuestos.

Para cada pregunta, haga que su programa muestre un string con formato, con la respuesta. Por ejemplo, para la primera pregunta, deberá imprimir el mensaje:

__"El precio promedio de todas las casas es $89345.34"__

Para hacer este taller, necesitará leer el archivo, y generar arreglos de NumPy paralelos.

Para esto, puedes leer el archivo línea por línea y separar los datos de la línea, y agregarlos a listas, y cuando ya tenga estas listas, puedes convertirlas a arreglos de NumPy usando np.array() un código similar a este:

In [1]:
import numpy as np

direccion,area,cuartos,banos,precio,pais
5 Nancy Parkway,95,5,3,165024,Gambia
6 Manufacturers Park,169,4,1,142173,Brazil
09 Michigan Circle,210,1,2,177667,Russia
8 Eastwood Center,180,3,1,146295,Ukraine
5 Coleman Street,181,5,3,164613,Colombia
67 Goodland Place,203,2,3,193336,Portugal
563 Sachtjen Court,169,2,2,92802,Thailand
4 Dayton Circle,117,3,1,91456,Afghanistan

In [ ]:
def datos(nomArchivo):
    l_direcciones = []
    l_areas = []
    l_cuartos = []
    l_banos = []
    l_precios = []
    l_paises = []
    f = open(nomArchivo, "r")
    f.readline()
    for linea in f:
        direccion,area,cuartos,banos,precio,pais = linea.strip().split(",")
        l_direcciones.append(direccion)
        l_areas.append(int(area))
        l_cuartos.append(int(cuartos))
        l_banos.append(int(banos))
        l_precios.append(float(precio))
        l_paises.append(pais)
        l_direcciones = []
    v_direcciones = np.array(l_direcciones)
    v_areas = np.array(l_areas)
    v_cuartos = np.array(l_cuartos)
    v_banos = np.array(l_banos)
    v_precios = np.array(l_precios)
    v_paises = np.array(l_paises)
    return v_areas,...

In [ ]:
def promedioCasas(v_precios):
    v_proms = v_precios.mean()
    return v_proms   

In [ ]:
def totalAreas(v_areas, v_cuartos, cuarto): # 3
    cuar = np.where(v_cuartos == cuarto)
    areas = v_areas[cuar]
    return areas.sum()

In [ ]:
def casasCaras(v_precios, v_cuartos,cuarto): #2
    pre = np.where(v_precio >= 10000)
    habit = np.where(v_cuartos == cuarto)
    cont = 0 
    for elem in pre: 
        if elem in habit:
            cont+=1
    return cont

In [ ]:
def casasCaras(v_precios, v_cuartos,cuarto, precio): #2 # 10000
    cond1 = v_precios >= precio
    cond2 = v_cuartos == cuarto
    cant = v_precios[cond1 == cond2].size
    return cant

In [ ]:
# Muestre las direcciones de las 4 casas más baratas, y sus precios.
def casasBaratas(v_precios,v_direciones,n): # n = 4
    orden = v_precios.argsort()
    top = orden[:n]
    d = v_direciones[top]
    return d

In [ ]:
#~De Las casas con 3 y 4 cuartos, muestre los países de las 2 casas con mayor precio
def casas_cuartos(v_cuartos,num1,num2): # 3,4
    ind1 = np.where(c==num1)[0] # ([0 3],)            [0 3]
    ind2 = np.where(c==num2)[0] # [2 4]
    l_ind1 = ind1.tolist()
    l_ind2 = ind2.tolist()
    l_ind1.extend(l_ind2)
    l_ind1
    v_inds = np.array(l_ind1)
    return v_inds
    

In [29]:
c = np.array([3,2,4,3,4]
pa = np.array(["A","B","C","D","F"])
p = np.random.randint(100,200,5)
print(c)
print(pa)
print(p)

[3 2 4 3 4]
['A' 'B' 'C' 'D' 'F']
[127 181 179 125 168]


In [36]:
c = np.array([3,2,4,3,4])
ind1 = np.where(c==3)[0] # ([0 3],)            [0 3]
ind2 = np.where(c==4)[0] # [2 4]
l_ind1 = ind1.tolist()
l_ind2 = ind2.tolist()
l_ind1.extend(l_ind2)
l_ind1
v_inds = np.array(l_ind1)
v_inds

print(pa[v_inds])
print(p[v_inds])

['A' 'D' 'C' 'F']
[127 125 179 168]


In [24]:
p= np.random.randint(100,200,5)
n = 3
d = np.array(["A","B","C","D","F"])
print(p)

[170 195 195 127 186]


In [27]:
orden = p.argsort()
top = orden[:n]
print(d[top])

['D' 'A' 'F']


In [7]:
v = np.where(a==3)
print(v)
print(a[v])


(array([0, 7, 9], dtype=int64),)
[3 3 3]


In [5]:
z= a==3
z

array([ True, False, False, False, False, False, False,  True, False,
        True])

In [17]:
c = np.array([0, 2, 3, 4])
h = np.array([2,3])
cont = 0 # 2
for elem in c: #
    if elem in h:
        cont+=1
print(cont)

2


In [23]:
c = np.array([3,2,2,2,5])
p = np.array([100,25,125,100,200])
cond1 = c==2
cond2 = p>=75 
print(cond1)
print(cond2)
print()
print(cond1 == cond2)
x = c[cond1== cond2].size
print(x)

[False  True  True  True False]
[ True False  True  True  True]

[False False  True  True False]
2
