# Taller NumPy 2D

En este taller, tendras dos arreglos 2D de NumPy:

* __arr_ventas__: arreglos con ventas en millones de dolares de medicinas en cada pais
* __arr_efectos__ efectos secundarios promedio observados en cada pais para cada medicina

Ambos arreglos tienen de filas las medicinas, y de columnas los paises. Tambien tienes las siguintes listas:

```python
medicinas =  ['Ibuprofeno', 'enzalutamida', ...]

america = ['Antigua and Barbuda', ...]
africa = ['Algeria', ...]
asia = ['Afghanistan', ...]
oceania = ['Australia', ...]
europa = ['Albania', ...]
```

Los paises en los arreglos estan en el siguiente orden: america, africa, asia, oceania y finalmente los paises de europa. Dentro de cada grupo, el orden de los paises es el mismo que en la lista correspondiente. Por ejemplo:

    Antigua y Barbuda ... | Algeria ...  | ... | Albania ... 

Entonces usando NumPy responde las siguientes preguntas (muestra respueta con formato):

1. ¿Cual es el total de ventas de de medicinas para Mexico?

2. ¿Cuál es la medicina más vendida y el pais?

3. ¿Cuales son las medicinas y paises con menos de 3 efectos secundarios? TIP: recuerda que si aplicas una condicion a un arreglo usando np.where(), la funcion te devolvera una arreglo de coordeandas (tuplas), que puedes usar para indexar el arreglo.

4. Muestra el promedio de ventas para el contiente asiatico

5. Muestra el nombre la medicina con menos ventas totales (y cuanto vendio)

6. Muestra los 5 paises con menos ventas totales de medicinas (solo el nombre)

7. Para cada continente, muestra la medicina que mas se vendio. TIP: usa slicing para seleccionar la parte del arreglo que tiene los datos que necesitas.

8. Para el continente africano, muestra la medicina que tiene, en promedio, menores efectos secundarios.


In [1]:
# funciones.py
import random as rd
import numpy as np

def cargarDatos():
    rd.seed(5)
    meds = []
    with open('medicinas.txt', 'r') as datafile:
        for linea in datafile:
            medicina = linea.strip()
            meds.append(medicina)

    continentes = {
        'Asia': [],
        'Africa': [],
        'Oceania': [],
        'America': [],
        'Europe': []
    }
    with open('paises.txt', 'r') as datafile:
        datafile.readline()
        for linea in datafile:
            data = linea.strip().split(',')
            pais = data[1]
            continente = data[0]
            if 'America' in continente:
                continente = 'America'
            continentes[continente].append(pais)

    paises = continentes['America'] + continentes['Africa'] + continentes['Asia'] + continentes['Oceania']  + continentes['Europe']
    arr_ventas = np.zeros((len(meds), len(paises)))
    arr_efectos = np.zeros((len(meds), len(paises)))

    for i in range(arr_ventas.shape[0]):
        for j in range(arr_ventas.shape[1]):
            arr_ventas[i, j] = abs(rd.gauss(150000000, 12000000))
            arr_efectos[i, j] = abs(rd.gauss(5,4))

    return list(meds), continentes['America'], continentes['Africa'], continentes['Asia'], continentes['Oceania'],    continentes['Europe'], arr_ventas, arr_efectos

In [2]:
medicinas, america, africa, asia, oceania, europa, arr_ventas, arr_efectos = cargarDatos()

In [8]:
arr_efectos

array([[ 0.40735728,  4.17564038,  4.02430907, ...,  3.11646579,
        10.0491753 , 11.66369069],
       [ 4.77150759,  8.8347162 ,  2.49396545, ...,  1.16739504,
         6.5526543 ,  6.47054225],
       [ 9.51528196,  9.1269283 ,  2.33679123, ...,  7.06879524,
         9.72505037,  9.58303673],
       ...,
       [ 9.7199847 ,  5.89127206,  9.70423042, ...,  7.35217095,
         6.19601789,  2.12344711],
       [11.59261654,  1.55190755,  5.11874885, ...,  9.29631064,
         8.10446039,  2.56125801],
       [ 6.00923476,  3.98044603,  4.3495852 , ...,  4.20651096,
         3.03588181,  1.82158221]])

In [20]:
E = np.random.randint(0,15,(4,6))
E

array([[13, 13,  5,  9,  9, 14],
       [ 4,  7,  8, 10, 14,  5],
       [ 9,  9, 14,  8,  7,  1],
       [ 6,  9, 12,  4,  5, 11]])

In [11]:
filas,cols = np.where(E<=3)
print(filas)
print(cols)

[0 0 0 1 1 2 2 2 3 3]
[2 3 4 0 1 0 3 4 0 4]


In [15]:
ind_m = np.unique(filas)
ind_p = np.unique(cols)
ind_p

array([0, 1, 2, 3, 4], dtype=int64)

In [3]:
# 1. ¿Cual es el total de ventas de de medicinas para Mexico?
l_paises = america+africa+asia+oceania+europa
v_paises = np.array(l_paises)
indi_pais = np.where(v_paises == 'Mexico')[0][0] #indice del pais
#print(indi_pais)
colu_mexi = arr_ventas[:,indi_pais]
suma_mexi =  colu_mexi.sum()
print('El total de ventas de de medicinas para Mexico: {} '.format(suma_mexi))

El total de ventas de de medicinas para Mexico: 8461652513.551634 


In [ ]:
# 2. ¿Cuál es la medicina más vendida y el pais?
# sacar el maximo de la matriz

#sacar el maximo
maxi = arr_ventas.max() # 95507
# iteramos elemento a elemento
columna = arr_venta.shape[1]
fila = arr_ventas.shape[0]
for i in range(fila):
    for j in range(columna):
        valor = arr_ventas[i,j]
        if valor == maxi:
            ind_fila = i
            ind_col = j
medi_mayor = medicinas[ind_fila]
pais_mayor = paises[ind_col]
   
#print(id_mayor)
print('La medicina más vendida es {} y el pais es {}'.format(medi_mayor,pais_mayor))


In [21]:
# 3. ¿Cuales son las medicinas y paises con menos de 3 efectos secundarios? 
v_filas,v_cols = np.where(E<=3)
inds_f = np.unique(v_filas)
inds_c = np.unique(v_cols)
v_medicinas = np.array(medicinas)
print(v_medicinas[inds_f])
print(v_paises[inds_c])

['C']
['china']


In [23]:
#6
paises_cantmenores = []
col_pais= M.shape[1]
for columna in range(col_pais):
    vents =  M[:,columna]
    sum_vents =  vents.sum()
    paises_cantmenores.append(sum_vents)
print(paises_cantmenores)
vector =  np.array(paises_cantmenores)
orden = vector.argsort()
print(orden)
inds_Top = orden[:3]
print(v_paises[inds_Top])
print('los 5 paises con menos ventas totales de medicinas son :')

[152057, 159192, 127897, 220347, 205813, 207418]
[2 0 1 4 5 3]
['W' 'Z' 'X']
los 5 paises con menos ventas totales de medicinas son :


In [7]:
import numpy as np
M = np.random.randint(0,100000,(4,6))
M

array([[ 9724, 71051, 15533, 29882, 65788, 69029],
       [23193, 31261, 15005, 37179,  7856, 95507],
       [44370, 35953, 51063, 66833, 60394, 15213],
       [74770, 20927, 46296, 86453, 71775, 27669]])

In [18]:
medicinas = ["A","B","C","D"]
america = ["Z","X"];africa = ["W","Y"]; asia=["corea","china"]
paises = america+africa+asia.
v_paises = np.array(paises)

In [ ]:
# Para cada continente, muestra la medicina que mas se vendio. 
ini_col = 0
dicc = {'ámerica':america,'áfrica':africa,'ásia':asia}
l_Med_cont = [] # A
for continente in dicc: #'ámerica'
    continentes =  len(dicc[continentes])
    final_columna = ini_col+continentes
    ini_col = final_columna
    M_cont= M[:,ini_col:final_columna]
    l_sumas = []
    filas = M_cont.shape[0]
    for i in range(filas): #1
        fila = M_cont[i,:]
        suma = fila.sum() #734223
        l_sumas.append(suma)
    v_sumas= np.array(l_sumas)
    ind = v_sumas.argmax()
    medicina = v_medicinas[ind] # A
    L_Med_cont.append(medicina)



    
    

In [ ]:
# Para cada continente, muestra la medicina que mas se vendio. 
ini_col = 0
dicc = {'ámerica':america,'áfrica':africa,'ásia':asia}
l_Med_cont = [] # A
for continente in dicc: #'ámerica'
    continentes =  len(dicc[continentes])
    final_columna = ini_col+continentes
    ini_col = final_columna
    M_cont= M[:,ini_col:final_columna]
    v_med_T = M_cont.sum(axis = 1)
    i_med_m = v_med_T.argmax()
    medicina = v_medicinas[i_med_m]
    l_Med_cont.append(medicina)

In [25]:
N = np.random.randint(0,10,(4,3))
N.sum(axis =1)

array([11, 13, 14, 16])